/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as TallerSlugRouteImport } from './routes/taller.$slug'
import { Route as AuthenticatedPanelIndexRouteImport } from './routes/_authenticated/panel.index'
import { Route as AuthenticatedPanelOnboardingRouteImport } from './routes/_authenticated/panel.onboarding'
import { Route as AuthenticatedPanelServiciosRouteImport } from './routes/_authenticated/panel.servicios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerSlugRoute = TallerSlugRouteImport.update({
  id: '/taller/$slug',
  path: '/taller/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelIndexRoute = AuthenticatedPanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelOnboardingRoute =
  AuthenticatedPanelOnboardingRouteImport.update({
    id: '/panel/onboarding',
    path: '/panel/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelServiciosRoute =
  AuthenticatedPanelServiciosRouteImport.update({
    id: '/panel/servicios',
    path: '/panel/servicios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reservar': typeof ReservarRoute
  '/taller/$slug': typeof TallerSlugRoute
  '/panel/onboarding': typeof AuthenticatedPanelOnboardingRoute
  '/panel/servicios': typeof AuthenticatedPanelServiciosRoute
  '/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reservar': typeof ReservarRoute
  '/taller/$slug': typeof TallerSlugRoute
  '/panel/onboarding': typeof AuthenticatedPanelOnboardingRoute
  '/panel/servicios': typeof AuthenticatedPanelServiciosRoute
  '/panel': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reservar': typeof ReservarRoute
  '/taller/$slug': typeof TallerSlugRoute
  '/_authenticated/panel/onboarding': typeof AuthenticatedPanelOnboardingRoute
  '/_authenticated/panel/servicios': typeof AuthenticatedPanelServiciosRoute
  '/_authenticated/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reservar'
    | '/taller/$slug'
    | '/panel/onboarding'
    | '/panel/servicios'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reservar'
    | '/taller/$slug'
    | '/panel/onboarding'
    | '/panel/servicios'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reservar'
    | '/taller/$slug'
    | '/_authenticated/panel/onboarding'
    | '/_authenticated/panel/servicios'
    | '/_authenticated/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReservarRoute: typeof ReservarRoute
  TallerSlugRoute: typeof TallerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/$slug': {
      id: '/taller/$slug'
      path: '/taller/$slug'
      fullPath: '/taller/$slug'
      preLoaderRoute: typeof TallerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel/': {
      id: '/_authenticated/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof AuthenticatedPanelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/onboarding': {
      id: '/_authenticated/panel/onboarding'
      path: '/panel/onboarding'
      fullPath: '/panel/onboarding'
      preLoaderRoute: typeof AuthenticatedPanelOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/servicios': {
      id: '/_authenticated/panel/servicios'
      path: '/panel/servicios'
      fullPath: '/panel/servicios'
      preLoaderRoute: typeof AuthenticatedPanelServiciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelOnboardingRoute: typeof AuthenticatedPanelOnboardingRoute
  AuthenticatedPanelServiciosRoute: typeof AuthenticatedPanelServiciosRoute
  AuthenticatedPanelIndexRoute: typeof AuthenticatedPanelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelOnboardingRoute: AuthenticatedPanelOnboardingRoute,
  AuthenticatedPanelServiciosRoute: AuthenticatedPanelServiciosRoute,
  AuthenticatedPanelIndexRoute: AuthenticatedPanelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReservarRoute: ReservarRoute,
  TallerSlugRoute: TallerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
